# Generated by Django 5.1.3 on 2024-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizerrequest',
            name='request_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='seedrequest',
            name='request_date',
            field=models.DateField(null=True),
        ),
    ]
