# Generated by Django 5.1.3 on 2024-12-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_fertilizerrequest_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='lastname',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
