# Generated by Django 5.1.3 on 2024-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_farmer_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronomist',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
