# Generated by Django 5.1.3 on 2024-12-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_agronomist_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedrequest',
            name='agronomist',
        ),
    ]
