# Generated by Django 5.1.3 on 2024-12-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_seedrequest_agronomist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeedRequest',
        ),
    ]
