# Generated by Django 5.1.3 on 2024-12-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_seedrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('agronomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.agronomist')),
            ],
        ),
    ]
