# Generated by Django 5.1.3 on 2024-12-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_seedrequest_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
