# Generated by Django 5.1.3 on 2024-12-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_seedrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedrequest',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
